name: Setup
description: Setup Node.js and install dependencies

inputs:
  skip-cache:
    description: Skip dependency caching
    required: false
    default: "false"

runs:
  using: composite
  steps:
    - name: Setup Node.js
      uses: actions/setup-node@v6
      with:
        node-version-file: .node-version
        registry-url: "https://registry.npmjs.org"

    - run: corepack enable
      shell: bash

    - name: Restore dependencies
      id: yarn-cache
      if: inputs.skip-cache != 'true'
      uses: actions/cache/restore@v4
      with:
        path: |
          **/node_modules
          .yarn/install-state.gz
        key: ${{ runner.os }}-yarn-${{ hashFiles('yarn.lock') }}-${{ hashFiles('**/package.json', '!node_modules/**') }}
        restore-keys: |
          ${{ runner.os }}-yarn-${{ hashFiles('yarn.lock') }}
          ${{ runner.os }}-yarn-

    - name: Install dependencies
      if: inputs.skip-cache == 'true' || steps.yarn-cache.outputs.cache-hit != 'true'
      run: yarn install --immutable
      shell: bash

    - name: Run yarn genversion
      run: yarn genversion
      shell: bash

    - name: Cache dependencies
      if: inputs.skip-cache != 'true' && steps.yarn-cache.outputs.cache-hit != 'true'
      uses: actions/cache/save@v4
      with:
        path: |
          **/node_modules
          .yarn/install-state.gz
        key: ${{ steps.yarn-cache.outputs.cache-primary-key }}
